version: '3.8'

services:
  # Backend - FastAPI (desde Docker Hub)
  backend:
    image: 2harold2/feel-guard-backend:v1.0.0
    container_name: feel-guard-backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=postgresql://user:password@postgres:5432/feelguard
      - SECRET_KEY=your-secret-key-here
      - OPENAI_API_KEY=your-openai-api-key-here
    volumes:
      - ./feel-guard-back/uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - feel-guard-network
    restart: unless-stopped

  # Frontend - React (desde Docker Hub)
  frontend:
    image: 2harold2/feel-guard-frontend:v1.0.0
    container_name: feel-guard-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - feel-guard-network
    restart: unless-stopped

  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: feel-guard-postgres
    environment:
      - POSTGRES_DB=feelguard
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - feel-guard-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  feel-guard-network:
    driver: bridge 